### ISSUE TITLE
Spectator item isn't give on death

### ISSUE THREAD

**Issue by Kebad45** [svilex/SkyWars-PocketMine#76] opened 2016-10-19 18:12 UTC
## Issue description

When a player die he doesn't receive the spectator item to go back to hub and the /sw quit command doesn't work too 
## Errors - CrashDumps

No errors
```
paste here or delete these lines
```

## Versions

- **SW_VERSION**: Last

- **POCKETMINE**: Genisys

- **PHP**: 7.0.2

**Comment by svilex** [comment] 2016-10-19 19:07
with "last" version, what do you mean?
Genisys version? mcpe version?
What exactly happens after a player dies?
Is spectator mode enabled in the plugin configs?

If would you like this bug to be fixed (if exists) , you need to reply to all the questions above giving as much info as you can because i will make a test and if i fail reproducing this bug, this issue will be closed and your bug won't be fixed.

If you can, upload a video showing the bug, this will help me understanding and will be a proof the bug really exists

**Comment by Kebad45** [comment] 2016-10-19 20:04
So the Genisys version i use is : ce1fd04, the version pf the sw is 0.6 and yea specate is enabled in the config

**Comment by Kebad45** [comment] 2016-10-19 20:04
death.spectator: true
spectator.quit.item: "120:1"

**Comment by Kebad45** [comment] 2016-10-19 20:05
death.spectator: true
spectator.quit.item: "120:1"

**Comment by Kebad45** [comment] 2016-10-19 20:05
Sorry i misclick

**Comment by svilex** [comment] 2016-10-19 20:10
0.6 isn't the last version of this plugin. download the code, make a phar and it should work. let me know :)

**Comment by Kebad45** [comment] 2016-10-20 05:21
Where i can find it ? Will try ;)

**Comment by svilex** [comment] 2016-10-20 05:27
You can find the code here, in this git repository. Obviusly you don't know what i'm talking about, so, i made a phar for you, download it from [here](http://pmt.mcpe.me/data/phars/phar_SkyWars-PocketMine-master_zplksXaqzXmCwqY.phar)

**Comment by Kebad45** [comment] 2016-10-20 16:52
It doesnt work too :/

**Comment by RedstoneAlmeida** [comment] 2016-10-21 15:05
is normaly from Genisys bug in Spectator Mode(Gamemode 3), to fix bug, is need fix a Spectator Mode direct from API or Skywars plugin

**Closed** 2016-10-21 20:37 UTC

**Comment by svilex** [comment] 2016-10-21 20:40
@RedstoneAlmeida nope, but i appreciate you've tried to help

@Kebad45 The quit item should now work, tested. Let me know

**Comment by Kebad45** [comment] 2016-10-22 08:42
Actually don't working too :/..
This is my stop function
    public function closePlayer(Player $p, $left = false, $spectate = false)
    {
        if ($this->quit($p->getName(), $left, $spectate)) {
            $p->gamemode = 4;//Just to make sure setGamemode() won't return false if the gm is the same
            $p->setGamemode($p->getServer()->getDefaultGamemode());
            $p->getInventory()->clearAll();
            $p->removeAllEffects();
            if ($p->isAlive()) {
                $p->setSprinting(false);
                $p->setSneaking(false);
                $p->extinguish();
                $p->setMaxHealth(20);
                $p->setMaxHealth($p->getMaxHealth());
                if ($p->getAttributeMap() != null) {//just to be really sure
                    $p->setHealth($p->getMaxHealth());
                    $p->setFood(20);
                }
            }
            if (!$spectate) {
                //TODO: Invisibility issues for death players
                $p->teleport($p->getServer()->getDefaultLevel()->getSpawnLocation());
            } elseif ($this->GAME_STATE == 1 && 1 < count($this->players)) {
                $p->gamemode = Player::SPECTATOR;
                $p->spawnToAll();
                $pk = new SetPlayerGameTypePacket();
                $pk->gamemode = Player::CREATIVE;
                $p->dataPacket($pk);                $pk = new AdventureSettingsPacket();               $pk->flags = 207;
               $pk->userPermission = 2;
                 $pk->globalPermission = 2;
                 $p->dataPacket($pk);
                $pk = new ContainerSetContentPacket();
                $pk->windowid = ContainerSetContentPacket::SPECIAL_CREATIVE;
                $p->dataPacket($pk);
                foreach ($this->players as $dname => $spawn) {
                    if (($d = $this->pg->getServer()->getPlayer($dname)) instanceof Player)
                        $d->hidePlayer($p);
                }
               $p->getInventory()->setHeldItemIndex(0);
$p->getInventory()->setItemInHand(Item::get(355,0,1)->setCustomName("Â§eLeave the game"));
                $p->getInventory()->setHeldItemIndex(1);
                //$p->getInventory()->setHotbarSlotIndex(0, 0);
                //$p->getInventory()->setHotbarSlotIndex(0, 0);
                $p->getInventory()->sendContents($p);
                $p->getInventory()->sendContents($p->getViewers());
                $p->sendMessage($this->pg->lang['death.spectator']);
            }
            return true;
        }
        return false;
    }

**Comment by svilex** [comment] 2016-10-22 09:04
@Kebad45 We are talking about this plugin, i don't want to know if you fork doesn't work

**Comment by Kebad45** [comment] 2016-10-22 09:27
I just change the setItemINHand and nothing else, why it doesn't work ? I think it's your plugin

**Comment by svilex** [comment] 2016-10-22 10:01
@Kebad45 Again: i don't care about your changes and i don't want to know why aren't working. This is not a forum.

We are here to fix a bug related to THIS plugin so, since i think i fixed the problem, i tested and it's working i would like to know from you if it also works for you, just to be sure.

So now if you CAN reply to my question:

-If the fix is working, ok
-If the fix isn't working, i will open the issue again, then, you will give me the steps needed to reproduce the issue and if i will be able to reproduce, i will try to fix

If you can't reply in the useful way explained above, then don't do it, but if you do, i will lock this issue and if you try to open another i will ban you from the repo. 

That's how it works

**Comment by svilex** [comment] 2016-10-22 11:46
If you are looking for a phar, [this](https://transfer.sh/VAOX1/sw-svile.phar) is the last
